name: tt_9
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  change_app_package_name: ^1.4.0
  google_fonts: ^6.2.1
  easy_date_timeline: ^1.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  intl: ^0.19.0
  pull_down_button: ^0.10.2
  flutter_svg: ^2.0.14
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SFProText-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFProText-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/SFProText-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProText-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SFProText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProText-SemiboldItalic.ttf
          weight: 600
          style: italic
